/* THIS FILE WAS GENERATED BY PAYLOAD CMS */
import configPromise from '@payload-config'
import { RootLayout } from '@payloadcms/next/layouts'
import { importMap } from '../importMap'

import '@payloadcms/next/css'

type Args = {
  children: React.ReactNode
}

const Layout = ({ children }: Args) => {
  return (
    <RootLayout
      config={configPromise}
      importMap={importMap}
      serverFunction={async (args) => {
        'use server'
        const { handleServerFunctions } = await import('@payloadcms/next/layouts')
        return handleServerFunctions({
          config: configPromise,
          importMap,
          serverFunctions: {},
          ...args,
        })
      }}
    >
      {children}
    </RootLayout>
  )
}

export default Layout
